# Generated by Django 3.2.9 on 2023-02-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housePointsApp', '0002_populate_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='students',
            field=models.IntegerField(default=0),
        ),
    ]
